language: node_js

node_js:
  - 6.9.1

env:
  - OC_VERSION=10.0

sudo: required

services:
  - docker

before_install:
  - docker pull owncloud:$OC_VERSION
  - DOCKER_ID=$(docker run -d -p 8888:80 owncloud:$OC_VERSION)

  - # needed else occ isn't available directly...
  - sleep 5

  - docker inspect $DOCKER_ID
  - docker exec -u www-data $DOCKER_ID ./occ maintenance:install --admin-user="admin" --admin-pass="admin" --database="sqlite"
  - docker exec -u www-data $DOCKER_ID ./occ config:system:set cors.allowed-domains 0 --value http://127.0.0.1:9876
  - docker exec -u www-data $DOCKER_ID ./occ config:system:set cors.allowed-domains 1 --value http://localhost:9876

script:
  - sleep 10
  - make browser
  - make test

after_script:
  - docker logs $DOCKER_ID
